apiVersion: v1
description: A Helm chart for Kubernetes (aps-cloud-connector-variables)
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: aps-cloud-connector-variables
version: 0.1.0
